name: Release

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
          cache: 'npm'
      - run: npm install --global yarn
      - run: yarn build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.dmg,dist/*.exe,dist/*.blockmap"
          token: ${{ github.token }}