name: Release

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.dmg,dist/*.exe,dist/*.blockmap"
          token: ${{ github.token }}